# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "shanghai"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
via_ir = true
out = "out"
script = "script"
solc = "0.8.27"
src = "src"
test = "test"
libs = ["node_modules"]

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 42161 }
avalanche = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 43114 }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 8453 }
bnb_smart_chain = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 56 }
gnosis_chain = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 100 }
goerli = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 5 }
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 1 }
optimism = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 10 }
polygon = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 137 }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 11155111 }
world = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain-id = 480 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
avalanche = "https://ava-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base = "https://mainnet.base.org"
bnb_smart_chain = "https://bsc-dataseed.binance.org"
gnosis_chain = "https://rpc.gnosischain.com"
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
localhost = "http://localhost:8545"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
world = "https://worldchain-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
